---
name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Checkout
        uses: actions/checkout@v3
      - run: cmake -B build -S . -G Ninja
      - run: cmake --build build
      - run: ctest --test-dir build -VV
